### ISSUE TITLE
Need flag for skip SSL certificate validatoin for self-signed certificates

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-lfs-migrate#10]

**Comment by DVGeoffrey** [comment]
+1 would like to see this feature.

**Comment by DVGeoffrey** [comment]
@bozaro do you have `ru.bozaro.gitlfs` up somewhere?

**Comment by bozaro** [comment]
@DVGeoffrey 
ru.bozaro.gitlfs is located at https://github.com/bozaro/git-lfs-java repository.

This module used in two my projects:

 * https://github.com/bozaro/git-as-svn
 * https://github.com/bozaro/git-lfs-migrate

**Comment by DVGeoffrey** [comment]
Just tried this [latest commit](https://github.com/bozaro/git-lfs-migrate/commit/357092b16879390d69ba0c1a1e4481a10831f2de) and am no longer getting cert errors.  Seems to be working!

**Comment by bozaro** [comment]
:)

**Comment by DVGeoffrey** [comment]
Unfortunately after the convert finished, I followed the instructions and ran `git fsck` and then tried a push, but it didn't seem to work.  Ie. the push worked, but when checking it out on another system I ran into "smudge" errors.  Looking at our GitHub Enterprise site, I don't see any entries in the "LFS" section for the repo pushed.

**Comment by DVGeoffrey** [comment]
When pushing I noticed there was no mention of LFS:
```
[root@rndsvn svn2devops_converted]# git push --mirror git@192.168.50.223:DevOps/Projects.git
Counting objects: 12293, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (11154/11154), done.
Writing objects: 100% (12293/12293), 13.88 MiB | 2.77 MiB/s, done.
Total 12293 (delta 5546), reused 0 (delta 0)
To git@192.168.50.223:DevOps/Projects.git
 * [new branch]      master -> master
 * [new branch]      svn/trunk -> svn/trunk
```

And then when cloning, the smudge error:
```
local:git-transition geoff$ git clone git@192.168.50.223:DevOps/Projects.git
Cloning into 'Projects'...
remote: Counting objects: 12293, done.
remote: Compressing objects: 100% (5608/5608), done.
remote: Total 12293 (delta 5546), reused 12293 (delta 5546), pack-reused 0
Receiving objects: 100% (12293/12293), 13.88 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (5546/5546), done.
Checking connectivity... done.
Downloading Puppet/modules/asis/files/Tools/PsExec.exe (378.69 KB)
Error accessing media: Puppet/modules/asis/files/Tools/PsExec.exe (3c26ef3208a8bf6c2a23d46ef15c238197f528c04877db0bac2a090d15ec53b2)

Errors logged to .git/lfs/objects/logs/20160118T162457.234190293.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: Puppet/modules/asis/files/Tools/PsExec.exe: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by bozaro** [comment]
As I known, ```git push --mirror``` don't upload LFS object. LFS objects uploaded by git-lfs-migrate tool (you need specify ```--lfs``` or ```--git``` parameter).

Can show git-lfs-migrate command, used for converting your repo?

P.S. I think write to closed issue is not good idea.

**Comment by DVGeoffrey** [comment]
You're right!  This fixed things... thanks!
