### ISSUE TITLE
git/lfs/migrate/Main : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by larsxschneider** [bozaro/git-lfs-migrate#11]
Hi,

when I run git-lfs-migrate, I get:

Exception in thread "main" java.lang.UnsupportedClassVersionError: git/lfs/migrate/Main : Unsupported major.minor version 52.0

This is my Java VM:
java -version
java version "1.6.0_35"
OpenJDK Runtime Environment (IcedTea6 1.13.7) (6b35-1.13.7-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

Any idea what might be wrong?

**Comment by bozaro** [comment]
You use too old Java version.
This project require Java 1.8+.

**Comment by bozaro** [comment]
Java 1.7 have end of support at April 2015.

**Comment by larsxschneider** [comment]
Thanks, that worked 👍
