### ISSUE TITLE
Batch request size is zero on retry.

### ISSUE THREAD

**Issue by sgoo** [bozaro/git-lfs-migrate#14]
If the initial conversion fails and a retry is attempted, the requests are all made with a `"size": 0`

This seems to be because data is saved into `git-lfs-migrate.mapdb`. When that data is reused in `git.lfs.migrate.GitConverter#createRemoteFile` the main body of that function is skipped so the size never gets set to anything other than zero.

Bitbucket.org's implementation of LFS asserts that the uploaded file matches in both OID and size.

**Comment by robinst** [comment]
I'm looking into this, looks like the cache will need to be changed.

**Comment by robinst** [comment]
PR for fix: https://github.com/bozaro/git-lfs-migrate/pull/16

**Comment by bozaro** [comment]
Fixed by PR #16
