### ISSUE TITLE
Convert files no extension

### ISSUE THREAD

**Issue by wesyq** [bozaro/git-lfs-migrate#20]
Hi,

Is there a way to convert files without an extension? For example, I tried this:

java -jar git-lfs-migrate.jar \ -s source.git \ -d dest.git \ -g https://example/lfs-test.git 
\ “*.clean” \ “*.log” \ “SAMPLEDATA”

But the file SAMPLEDATA did not get converted to LFS. Is there a way to accomplish this?

Thanks.

**Comment by bozaro** [comment]
You command looks like really strange (it has strange quotes and slashes).
Looks like it shold be like:
```
java -jar git-lfs-migrate.jar -s source.git -d dest.git -g https://example/lfs-test.git .clean "*.log" SAMPLEDATA
```

**Comment by wesyq** [comment]
I tried it without the quotes and slashes too, but the files without extensions don't seem to be filtered. This feature to filter extension-less files would be really cool if possible :) If you have already tested it, then may be it is a matter of my environment. I am using Windows. Although I can try it on Mac too.

Btw, thanks for such a great tool, it has really helped me and my migration team :)

**Comment by bozaro** [comment]
Really. Wildcards was processed incorrectly. Fixed.

**Comment by bozaro** [comment]
Not fixed yet :(

**Comment by bozaro** [comment]
I try to fix pattern matching and it works much better.
But unfortunatelly it still not fully correct. I fix this issue something later on this week.

**Comment by wesyq** [comment]
Hi,

Did you get a chance to fix it? :)

**Comment by bozaro** [comment]
If you use only name patterns and don't use path patterns (like "foo/*.zip"), you can safety use version from master branch.
Correct fix shoud be some later.

**Comment by wesyq** [comment]
Okay, thanks. I will try it. Although the build is failing, but only due to a test assertion, the code can be tried as you said it should be working fine safely.

**Comment by wesyq** [comment]
I managed to convert extension-less files by building the source from master. Thanks a ton!

**Comment by wesyq** [comment]
Also, I noticed that I no longer need to place the backslashes '\' in the newer build, and it worked. In the earlier releases, I had to put the backslashes in the command. But not anymore. This is also an improvement.
