### ISSUE TITLE
text vs crlf in .gitattributes

### ISSUE THREAD

**Issue by leth** [bozaro/git-lfs-migrate#25]
Hi, I noticed the lines this tool adds to `.gitattributes` differ from lines added by `git lfs track`.
The migrate tool adds `-crlf` where as track adds `-text`.

Is this something that needs to be fixed, or is this correct?
Thank

**Comment by bozaro** [comment]
Thanks for attension.
This option was change in `git-lfs` by commit: https://github.com/git-lfs/git-lfs/commit/7146bdb130e79756be17801cba7cf17763ec95f4
