### ISSUE TITLE
SimpleHttpConnectionManager warning

### ISSUE THREAD

**Issue by boblaublaw** [bozaro/git-lfs-migrate#4]
Oct 19, 2015 5:16:20 PM org.apache.commons.httpclient.SimpleHttpConnectionManager getConnectionWithTimeout
WARNING: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.

**Comment by bozaro** [comment]
I did not notice this warning. Will check in soon.

**Comment by bozaro** [comment]
Fixed in https://github.com/bozaro/git-lfs-migrate/releases/tag/0.0.14
