### ISSUE TITLE
Support an arbitrary glob, not just a suffix

### ISSUE THREAD

**Issue by apskim** [bozaro/git-lfs-migrate#8]
`git-lfs` can take an arbitrary glob path as an argument. In my case I need to track something like `**/config/*.xml` (only those XMLs, not _all_ XMLs). Can you please upgrade `git-lfs-migrate` to take an LFS-compatible glob instead of a list of suffixes?

**Comment by bozaro** [comment]
The feature will be implemented soon under #9.
